### PR TITLE
Update cryptosuite names and remove some trailing whitespace.

### PR DESCRIPTION
**Pull request by dlongley**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vp-request-spec/pull/34.html" title="Last updated on Jul 16, 2024, 6:25 PM UTC (0d28182)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/vp-request-spec/34/1175f5a...0d28182.html" title="Last updated on Jul 16, 2024, 6:25 PM UTC (0d28182)">Diff</a>

### CODE REVIEW

**Comment by dlongley** [comment]
This PR also fixes an old reference to the prospective VC 2.0 context to match the new VC 2.0 context URL.

**Review by TallTed — CHANGES_REQUESTED** [review]
Replace "utilize" with "use"

**Comment by dlongley** [comment]
@TallTed, applied, thanks!

**Comment by dlongley** [comment]
Merging as editorial fixes to examples.

**Pull request merged**
